#! /usr/bin/python3
import sys
sys.path.append('/usr/share/lliurex-shutdowner/')

import LliurexShutdowner

if __name__=="__main__":
	
	args={}
	args["gui"]=True
	args["server"]="server"
	ls=LliurexShutdowner.LliurexShutdowner(args)
	